name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch: # To run manually

jobs:

  Test Project:

    runs-on: ubuntu-latest

    steps:
    - name: check out project
      uses: actions/checkout@v3
      
    - name: set up jdk 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
  
    - id: file_changes
      name: File Changes
      uses: trilom/file-changes-action@v1.2.3
    
    - name: Ouput File Changes
      run: echo '$'
      
    - if: contains(steps.file_changes.outputs.files , '"tdd/')
      name: Build Maven Project
      run: |
        echo "Running test on path"
        pwd
        mvn test --file tdd/pom.xml



#    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
#    - name: Update dependency graph
#      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
