name: Test | Build | Deploy

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '.github/**'

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '.github/**'

  workflow_dispatch: # To run manually

jobs:

  Test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v3
      
    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
  
    - id: file_changes
      name: File Changes
      uses: trilom/file-changes-action@v1.2.3
         
    - if: contains(steps.file_changes.outputs.files , 'tdd/')
      name: Build Maven Project
      run: |
        mvn test --file tdd/pom.xml
        
